#ifndef __EVEAPIDATATYPE_HH__
#define __EVEAPIDATATYPE_HH__

enum ParsedDataType
{
    PDT_NULL,
    PDT_SKILLTREE,
    PDT_REFTYPES,
    PDT_SOVEREIGNTY,
    PDT_CHARSHEET,
    PDT_SKILLINTRAINING,
    PDT_WALKED,
    PDT_ACCOUNTBALANCE,
    PDT_MEMBERTRACKING
};

#endif
